import 'package:mobx/mobx.dart';
part 'my_model.g.dart'; // This will be generated by the MobX code generator
class MyModel = _MyModel with _$MyModel;
abstract class _MyModel with Store {
  @observable
  String name = '';

  @observable
  int age = 0;

  @action
  void setName(String newName) {
    name = newName;
  }

  @action
  void setAge(int newAge) {
    age = newAge;  }}